const styles = {
    container: {

        display: 'flex',
        fontFamily: 'Arial, sans-serif',
        backgroundColor: '#f5f5f5',
        height: 'auto',
        position: 'relative',
    },
    sidebar: {
        width: '220px',
        padding: '20px',
        boxShadow: '2px 0 5px rgba(0, 0, 0, 0.1)',
        color: '#fff',
        display: 'flex',
        flexDirection: 'column',
    },
    sidebarTitle: {
        marginBottom: '20px',
        fontSize: '18px',
        color: '#fff',
    },
    sidebarButton: {
        display: 'block',
        width: '100%',
        padding: '10px',
        marginBottom: '10px',
        backgroundColor: '#007BFF',
        color: '#fff',
        border: 'none',
        borderRadius: '5px',
        cursor: 'pointer',
    },
    previewButton: {
        fontSize: '16px',
        backgroundColor: '#28a745',
        color: '#fff',
        border: 'none',
        cursor: 'pointer',
        display: 'block',
        width: '100%',
        padding: '10px',
        marginBottom: '10px',
        borderRadius: '5px',
    },
    mainContent: {
        flexGrow: 1,
        padding: '20px',
        boxSizing: 'border-box',
    },
    articleWindow: {
        backgroundColor: '#fff',
        padding: '20px',
        borderRadius: '10px',
        boxShadow: '0 0 10px rgba(0, 0, 0, 0.1)',
        minHeight: '400px',
    },
    placeholderText: {
        color: '#888',
        fontSize: '18px',
        textAlign: 'center',
        marginTop: '40px',
    },
    modalContent: {
        padding: '20px',
        textAlign: 'center',
    },
    downloadButton: {
        padding: '10px 20px',
        fontSize: '18px',
        backgroundColor: '#ffc107',
        color: '#fff',
        border: 'none',
        borderRadius: '5px',
        cursor: 'pointer',
        marginTop: '20px',
    },

    blockContainer: {
        display: 'flex',
        position: 'relative',
        padding: '10px',
        border: '1px solid #ddd',
        borderRadius: '8px',
        marginBottom: '15px',
        backgroundColor: '#fff',
    },
    deleteButton: {
        position: 'absolute',
        top: '10px',
        right: '10px',
        backgroundColor: 'transparent',
        border: 'none',
        fontSize: '18px',
        color: '#444',
        cursor: 'pointer',
        fontWeight: 'bold',
    },

    buttonContainer: {
        width: '30px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: '5px',
        marginLeft: '10px',
        marginTop: '30px',
    },

    moveButtonUp: {
        backgroundColor: '#f0f0f0',
        border: '1px solid #ccc',
        borderRadius: '50%',
        fontSize: '14px',
        color: '#444',
        cursor: 'pointer',
        width: '24px',
        height: '24px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },

    moveButtonDown: {
        backgroundColor: '#f0f0f0',
        border: '1px solid #ccc',
        borderRadius: '50%',
        fontSize: '14px',
        color: '#444',
        cursor: 'pointer',
        width: '24px',
        height: '24px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
    },

    confirmationLabel: {
        display: 'flex',
        alignItems: 'center',
        fontSize: '14px',
        color: '#000',
        margin: '15px 0',
    },
};

export default styles;
